### ISSUE TITLE
Support to modify VersionPrefix and automatically increment a specified portion of the semantic version

### ISSUE THREAD

**Issue by ronnyek** [TAGC/dotnet-setversion#21]
I'm looking at using this as a part of CI around nuget packages, and currently use VersionPrefix to build release versions based on build dates etc.

so 
``` xml
<VersionPrefix>3.1.0.1</VersionPrefix>
```
will produce ci builds of `3.1.0.1-ci-<YYYYMMDDBB>`

What I'd like to be able to do is say ok I want to publish a release version, and have that just be incrementing 3.1.0.1 by one minor version and publish it as such, and then continue to build additional postfixed builds from that.

I'd think that would require first being able to use this to specify which version to update (VersionPrefix vs Version) and then also be able to tell it to increment so I don't have to know exactly what the prefix version is., just tell it to incremement minor or something.

Does this seem like reasonable functionality to add to this project?

**Comment by TAGC** [comment]
> I'd think that would require first being able to use this to specify which version to update (VersionPrefix vs Version) and then also be able to tell it to increment so I don't have to know exactly what the prefix version is., just tell it to incremement minor or something.

So I think this can be split into two feature requests:

- Support setting `<VersionPrefix>` instead of `<Version>` in *.csproj files
- Support incrementing version numbers via the tool

I think the first one of these could be a good fit and worth adding. The second one I'm not sure about because this tool aims to avoid doing version calculations itself and really just takes a version string that's provided to it and writes it to one or more csproj files. For my own use, I typically use [GitVersion](https://github.com/GitTools/GitVersion) for the sort of "heavy lifting" aspect to calculate the version string and then use this tool to write that to the csproj files.

In your case, I would try to use a separate tool (or script) to calculate the minor-bumped version prefix (3.1.0.1 -> 3.2.0.1) and then update the csproj file using something like maybe `setversion --prefix 3.2.0.1`. Does that work?

**Comment by TAGC** [comment]
I'm going to close this as there's not been any response.
