### ISSUE TITLE
Support for .NET 8

### ISSUE THREAD

**Issue by paulirwin** [TAGC/dotnet-setversion#28]
.NET 8 LTS is now generally available, and the tool requires .NET 7 to be installed in a CI environment currently. Updating the project to support .NET 8 will help set it up for the next three years of LTS support.

**Comment by TAGC** [comment]
Thanks for raising this Paul. I'd like to get your PR merged but it doesn't look like AppVeyor has a Visual Studio image that includes the .NET 8 SDK yet. I don't expect it will be too long before they release an image with .NET 8 included.

**Comment by paulirwin** [comment]
@TAGC Thanks! What are your thoughts on removing .NET Core 2.1, .NET Core 3.1, and .NET 5 support now that they are out of support by Microsoft? Building locally gives lots of warnings about security vulnerabilities as a result of still targeting them.

**Comment by TAGC** [comment]
@paulirwin I think that's definitely a good shout. I'll probably release one version with just the .NET 8 upgrade in place and then another one that removes support for those three unsupported versions.

**Comment by TAGC** [comment]
Hi @paulirwin, I've released a prerelease package (`3.0.0-alpha0004`) that incorporates the changes from #31. I've tested it locally and it seems to work okay. I've changed my mind and think I might incorporate .NET 8 support (when it's ready) as part of the same upcoming stable release (`3.0.0`), rather than split them across two releases.

**Comment by paulirwin** [comment]
@TAGC Sounds good, I just updated my .NET 8 PR with merging in the latest changes from develop.
